/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tranginc_trangnhe_voicerecorderdemo_LameWrapper */

#ifndef _Included_com_tranginc_trangnhe_voicerecorderdemo_LameWrapper
#define _Included_com_tranginc_trangnhe_voicerecorderdemo_LameWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tranginc_trangnhe_voicerecorderdemo_LameWrapper
 * Method:    initEncoder
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_com_tranginc_trangnhe_voicerecorderdemo_LameWrapper_initEncoder
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     com_tranginc_trangnhe_voicerecorderdemo_LameWrapper
 * Method:    destroyEncoder
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tranginc_trangnhe_voicerecorderdemo_LameWrapper_destroyEncoder
  (JNIEnv *, jobject);

/*
 * Class:     com_tranginc_trangnhe_voicerecorderdemo_LameWrapper
 * Method:    encodeFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_tranginc_trangnhe_voicerecorderdemo_LameWrapper_encodeFile
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
